image: ubuntu:questing-20251217

# Derived from https://github.com/cachix/install-nix-action/blob/master/install-nix.sh
before_script: |
  enable_kvm() {
    echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | tee /etc/udev/rules.d/99-install-nix-action-kvm.rules
    udevadm control --reload-rules && sudo udevadm trigger --name-match=kvm
  }

  echo '::group::Enabling KVM support'
  enable_kvm && echo 'Enabled KVM' || echo 'KVM is not available'
  echo '::endgroup::'

  apt update && apt install curl ca-certificates

  nixConfig=$(mktemp)
  cat<<EOF > "$nixConfig"
  experimental-features = nix-command flakes pipe-operator
  access-tokens = gitlab.com=$AUTOMATION_ACCESS_TOKEN github.com=$GITHUB_TOKEN
  trusted-users = root
  EOF

  sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon --no-channel-add --nix-extra-conf-file "$nixConfig"

  export NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
  export NIX_LINK="$NIX_STATE_HOME/profile"
  export NIX_PROFILES="/nix/var/nix/profiles/default $NIX_LINK"
  export PATH="/nix/var/nix/profiles/default/bin:$NIX_LINK/bin:${PATH:-}"

stages:
  - check
  - update

nix-flake-check:
  stage: check
  script:
    - nix flake check -L
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"


nix-flake-update:
  stage: update
  before_script: |
    nix profile add nixpkgs#git nixpkgs#glab
    git config --global user.email ${GITLAB_USER_EMAIL}
    git config --global user.name ${GITLAB_USER_NAME}
    git remote set-url origin https://oauth2:${AUTOMATION_ACCESS_TOKEN}@${CI_PROJECT_URL#https://}.git
    glab auth login --hostname $CI_SERVER_HOST --job-token $AUTOMATION_ACCESS_TOKEN
  script: |
    echo "chore: nix flake update" > commitmsg
    echo >> commitmsg
    nix flake update 2>&1 | tee -a commitmsg
    git commit -aF commitmsg
    branchname="push-$(git rev-parse --short HEAD)"
    git switch -c "$branchname"
    glab mr create --fill --fill-commit-body --source-branch "$branchname" --push --yes
  after_script: |
    nix profile remove git glab

  rules:
    - if: $ACTION == "nix-flake-update"