keys:
  - &boomer age1p0qcwy8he6y70xk5qkp52pnaeyr2pdhhhgpjqgaxpwpu0dthhs8s099w9x
  - &feather age1pjgmdxkj6zvn5hpjwd4mlv2jw89mk78luuetdcjqtmaq6r88juwshyjqal
#  - &kaput age1e79848cgter0l5vtmk89tkgtk5727u3scsz5z0r7ngtvu2utmq4sj34l0v

creation_rules:
  - path_regex: secrets/[^/]+.secret
    key_groups:
      - age:
        - *boomer
        - *feather
        # - *kaput
