keys:
- &boomer age1p08uvpumsx02aj73dlww4sjz4qtkzpdc03cq4sglu205jq4kzfesklulr9
- &feather age1gj2dmrhgcfde0s49yyr92wdv7e44wf5949ygc4mhrxywhr4tdpastk0ze2

creation_rules:
- key_groups:
  - age:
    - *boomer
    - *feather
  path_regex: secrets/[^/]+.secret
