keys:
  - &boomer age1p08uvpumsx02aj73dlww4sjz4qtkzpdc03cq4sglu205jq4kzfesklulr9
  - &feather age1pjgmdxkj6zvn5hpjwd4mlv2jw89mk78luuetdcjqtmaq6r88juwshyjqal
  - &kaput age1vy2jtljumsxfa8uskvkjzha4hm9hwlmc8d3znu56tguq5ymzpqlslvnt94

creation_rules:
  - path_regex: secrets/[^/]+.secret
    key_groups:
      - age:
        - *boomer
        - *feather
        - *kaput
