name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - hoofdlijn
jobs:
  publish:
    runs-on: jorge
    steps:
      - uses: actions/checkout@v6
      - run: bash modules/services/blog/build.sh
      - uses: actions/git-pages@v2
        with:
          site: https://toostveen.nl
          token: ${{ forge.token }}
          source: modules/services/blog/target
