name: ags-customization

windows:
  - editor:
      layout: main-vertical
      panes:
        - editor:
          - nvim widget/Bar.tsx
        - ags:
          - watchexec --restart -e 'ts,tsx,scss' ags run $(pwd)
