name: "Tom Oostveen"
author: "Tom Oostveen"
url: "https://toostveen.nl"
description: "Placeholder"
highlight_theme: catppuccin-mocha
post_format: ":year-:month-:day-:title.md"
contact:
  - name: PGP
    href: https://keyoxide.org/91C74999F109AE74854AC519EFD11A9B09D8D2C6
  - name: IM
    href: https://matrix.to/#/@tom:toostveen.nl
  - name: SCM
    href: https://git.toostveen.nl/tom
  - name: MS-SCM
    href: https://github.com/dtomvan
  - name: MAIL
    href: mailto:tomoostveen.06@gmail.com
  - name: TOOT
    href: https://toot.cat/@dtomvan
