#!/usr/bin/env bash

set -euo pipefail

declare empty_file

log() {
    gum log -l info -t rfc3339 $@
}

bail() {
    gum log -l fatal -t rfc3339 $@
    if [ -f "$empty_file" ]; then rm -f "$empty_file"; fi
    exit 1
}

which unoconv >/dev/null || bail Unoconv not found. Cannot run creation script.

name="$(gum input --placeholder='ODT name' --cursor.mode="static" --header='Specify a document name, without extension' --width=0)" || bail 'no such document name'
dest="$name.odt"
log Destination will be $dest

if [ -e "$dest" ]; then
    log $dest already exists.
    bail Cannot overwrite existing file. Please specify a non-existing path.
fi

templates=($(fd -a . /usr/lib/libreoffice/share/template/ -e ott | sort))
template_chosen="$(gum choose --header="Template:" --ordered --height=5 --no-show-help ${templates[@]})" || bail 'Please choose a template.'

log Using template $template_chosen

empty_file="$(mktemp -p ~/.cache/ -t XXX)"
gum spin --show-error --title='converting...' -- unoconv -f odt -o "$dest" "$empty_file" \
    || bail Unoconv had an error. Exiting.

rm -f "$empty_file"

if gum confirm 'Open in soffice?' --no-show-help --affirmative='Open in soffice' --negative='Cancel'; then
    soffice "$dest" &
    disown
    exit 0
fi
