jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - env:
        LOCALSEND_TOKEN: ${{ secrets.LOCALSEND_TOKEN }}
      run: nix flake check -L --extra-access-tokens "github.com=$LOCALSEND_TOKEN"
'on':
  pull_request: {}
  push:
    branches:
    - main
