jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - env:
        GH_TOKEN: ${{ secrets.LOCALSEND_TOKEN }}
      name: Check that access token works
      run: gh api repos/dtomvan/localsend-rust-impl >/dev/null
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.LOCALSEND_TOKEN }}
    - name: Get vs2nix pulls
      run: 'vs2nix_pulls="$(gh api repos/dtomvan/vs2nix/pulls | jq -r ''map(select(.user.login
        == "github-actions[bot]") | "- \(.html_url)") | .[]'')"

        printf "MERGE_FIRST=''%s''" "$vs2nix_pulls" >> "$GITHUB_ENV"

        '
    - uses: DeterminateSystems/update-flake-lock@v27
      with:
        branch: update_flake_lock_action
        commit-msg: 'chore: nix flake update'
        pr-body: '```

          {{ env.GIT_COMMIT_MESSAGE }}

          ```


          @dtomvan (ping for GH mobile)


          Merge first:

          {{ env.MERGE_FIRST }}

          '
        pr-title: 'chore: nix flake update'
    - run: "nix run .#write-flake\nnix run .#write-files\nnix fmt\n\nif [[ \"$(git\
        \ status --porcelain | wc -l)\" -gt 0 ]]; then\n  git commit -am 'chore: sync\
        \ files after flake update'\n  git push origin update_flake_lock_action\n\
        fi\n"
'on':
  schedule:
  - cron: 0 5 * * 0
  workflow_dispatch: {}
